// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quiz.Infrastructure.Persistence;

#nullable disable

namespace Quiz.Infrastructure.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    [Migration("20260318202724_Added_new_questions")]
    partial class Added_new_questions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Quiz.Domain.Entities.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnswerText = "Waar",
                            IsCorrect = true,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 2,
                            AnswerText = "Niet Waar",
                            IsCorrect = false,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 3,
                            AnswerText = "Waar",
                            IsCorrect = true,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 4,
                            AnswerText = "Niet Waar",
                            IsCorrect = false,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 5,
                            AnswerText = "Waar",
                            IsCorrect = false,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 6,
                            AnswerText = "Niet Waar",
                            IsCorrect = true,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 7,
                            AnswerText = "Waar",
                            IsCorrect = true,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 8,
                            AnswerText = "Niet Waar",
                            IsCorrect = false,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 9,
                            AnswerText = "Meer",
                            IsCorrect = true,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 10,
                            AnswerText = "Minder",
                            IsCorrect = false,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 11,
                            AnswerText = "Hoger",
                            IsCorrect = false,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 12,
                            AnswerText = "Lager",
                            IsCorrect = true,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 13,
                            AnswerText = "Meer",
                            IsCorrect = false,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 14,
                            AnswerText = "Minder",
                            IsCorrect = true,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 15,
                            AnswerText = "Meer",
                            IsCorrect = false,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 16,
                            AnswerText = "Minder",
                            IsCorrect = true,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 17,
                            AnswerText = "A. Mars",
                            IsCorrect = false,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 18,
                            AnswerText = "B. Saturnus",
                            IsCorrect = false,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 19,
                            AnswerText = "C. Jupiter",
                            IsCorrect = true,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 20,
                            AnswerText = "D. Neptunus",
                            IsCorrect = false,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 21,
                            AnswerText = "A. 1985",
                            IsCorrect = false,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 22,
                            AnswerText = "B. 1989",
                            IsCorrect = true,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 23,
                            AnswerText = "C. 1991",
                            IsCorrect = false,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 24,
                            AnswerText = "D. 1993",
                            IsCorrect = false,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 25,
                            AnswerText = "A. Harry Mulisch",
                            IsCorrect = true,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 26,
                            AnswerText = "B. Maarten 't Hart",
                            IsCorrect = false,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 27,
                            AnswerText = "C. Cees Nooteboom",
                            IsCorrect = false,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 28,
                            AnswerText = "D. Gerard Reve",
                            IsCorrect = false,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 29,
                            AnswerText = "A. Harry Mulisch",
                            IsCorrect = true,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 30,
                            AnswerText = "B. Maarten 't Hart",
                            IsCorrect = false,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 31,
                            AnswerText = "C. Cees Nooteboom",
                            IsCorrect = false,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 32,
                            AnswerText = "D. Gerard Reve",
                            IsCorrect = false,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 33,
                            AnswerText = "A. Badminton",
                            IsCorrect = false,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 34,
                            AnswerText = "B. Tennis",
                            IsCorrect = true,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 35,
                            AnswerText = "C. Cricket",
                            IsCorrect = false,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 36,
                            AnswerText = "D. Squash",
                            IsCorrect = false,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 37,
                            AnswerText = "Waar",
                            IsCorrect = false,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 38,
                            AnswerText = "Niet Waar",
                            IsCorrect = true,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 39,
                            AnswerText = "Meer",
                            IsCorrect = true,
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 40,
                            AnswerText = "Minder",
                            IsCorrect = false,
                            QuestionId = 15
                        });
                });

            modelBuilder.Entity("Quiz.Domain.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MediaType")
                        .HasColumnType("int");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuizTemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizTemplateId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MediaType = 0,
                            QuestionText = "Is de eiffeltoren hoger dan 300 meter?",
                            QuizTemplateId = 1
                        },
                        new
                        {
                            Id = 2,
                            MediaType = 0,
                            QuestionText = "Heeft Nederland meer fietsen dan inwoners?",
                            QuizTemplateId = 1
                        },
                        new
                        {
                            Id = 3,
                            MediaType = 0,
                            QuestionText = "Is de mens de snelste landzoogdier ter wereld?",
                            QuizTemplateId = 1
                        },
                        new
                        {
                            Id = 4,
                            MediaType = 0,
                            QuestionText = "Ligt Australië op het zuidelijk halfrond?",
                            QuizTemplateId = 1
                        },
                        new
                        {
                            Id = 5,
                            MediaType = 0,
                            QuestionText = "Heeft een octopus meer of minder dan 6 armen?",
                            QuizTemplateId = 3
                        },
                        new
                        {
                            Id = 6,
                            MediaType = 0,
                            QuestionText = "Ligt de gemiddelde lichaamstemperatuur van een mens hoger of lager dan 38 graden Celsius?",
                            QuizTemplateId = 3
                        },
                        new
                        {
                            Id = 7,
                            MediaType = 0,
                            QuestionText = "Heeft een jaar meer of minder dan 400 dagen?",
                            QuizTemplateId = 3
                        },
                        new
                        {
                            Id = 8,
                            MediaType = 0,
                            QuestionText = "Is de afstand van Amsterdam naar Parijs meer of minder dan 500 kilometer?",
                            QuizTemplateId = 3
                        },
                        new
                        {
                            Id = 9,
                            MediaType = 0,
                            QuestionText = "Welke planeet is het grootst in ons zonnestelsel?",
                            QuizTemplateId = 2
                        },
                        new
                        {
                            Id = 10,
                            MediaType = 0,
                            QuestionText = "In welk jaar viel de Berlijnse Muur?",
                            QuizTemplateId = 2
                        },
                        new
                        {
                            Id = 11,
                            MediaType = 0,
                            QuestionText = "Wie schreef het boek 'De Ontdekking van de Hemel'?",
                            QuizTemplateId = 2
                        },
                        new
                        {
                            Id = 12,
                            MediaType = 0,
                            QuestionText = "Welk element heeft het chemische symbool 'Au'?",
                            QuizTemplateId = 2
                        },
                        new
                        {
                            Id = 13,
                            MediaType = 0,
                            QuestionText = "Welke sport wordt gespeeld bij Wimbledon?",
                            QuizTemplateId = 2
                        },
                        new
                        {
                            Id = 14,
                            MediaType = 0,
                            QuestionText = "Is de walvis een vis?",
                            QuizTemplateId = 1
                        },
                        new
                        {
                            Id = 15,
                            MediaType = 0,
                            QuestionText = "Heeft een mens meer of minder dan 200 botten in zijn lichaam?",
                            QuizTemplateId = 3
                        });
                });

            modelBuilder.Entity("Quiz.Domain.Entities.QuizTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemplateType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("QuizTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "True or False",
                            TemplateType = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Multiple Choice",
                            TemplateType = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "More or Less",
                            TemplateType = 3
                        });
                });

            modelBuilder.Entity("Quiz.Domain.Entities.Answer", b =>
                {
                    b.HasOne("Quiz.Domain.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Quiz.Domain.Entities.Question", b =>
                {
                    b.HasOne("Quiz.Domain.Entities.QuizTemplate", "QuizTemplate")
                        .WithMany()
                        .HasForeignKey("QuizTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizTemplate");
                });

            modelBuilder.Entity("Quiz.Domain.Entities.Question", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
